version: 2
jobs:
  test:
    docker:
      - image: python:3.6
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -r requirements_tests.txt
      - run:
          name: running tests
          command: |
            nosetests python_metrics_client/tests
  deploy:
    docker:
      - image: python:3.6
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: publish to geru-pypi
          command: |
            python setup.py sdist
            pip install twine
            twine upload --repository-url https://geru-pypi.geru.com.br/ dist/*

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
