version: 2
jobs:
  tests:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Tests
          command: |
            pip install -e .[tests]
            tox
  release:
    docker:
      - image: python:3.6
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: publish to geru-pypi
          command: |
            python setup.py sdist
            pip install twine
            twine upload --repository-url https://geru-pypi.geru.com.br/ dist/*

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - tests
      - release:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
